[package]
name = "p4stdtest"
version = "0.1.0"
edition = "2024"
resolver = "2"

[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "waveshare/esp_lcd_jd9365", version = "^1.0.6" }
bindings_header = "bindings.h"

[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "waveshare/esp_lcd_hx8394", version = "^1.0.3" }
bindings_header = "bindings.h"

[[bin]]
harness = false  # do not use the built-in cargo test harness -> resolve rust-analyzer errors
name = "p4stdtest"

[dependencies]
# Remove `generic-queue-8` if you plan to use `embassy-time` WITH `embassy-executor`
embassy-time = { version = "0.5", features = ["generic-queue-8"] }
embedded-graphics = "0.8.0"
esp-idf-svc = { version = "0.52.1", features = [
  "critical-section",
  "embassy-sync",
  "embassy-time-driver"
] }
log = "0.4"
lv_bevy_ecs = { version = "0.9.2", features = ["critical-section", "rust-alloc"] }

[build-dependencies]
embuild = "0.33"

[profile.dev]
opt-level = "z"
debug = true  # Symbols are nice, and they don't increase the size on Flash

[profile.release]
opt-level = "s"
